import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '/src/styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'

// component
import Ads from '/src/components/ads'
import LatestVideo from 'components/home/latestVideo'
import TopBrands from '/src/components/home/topbrands'

export default function Home() {
  return (
    <>
      <Head>
        <title>Female Daily</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* adsense */}
          <Ads cssName="TopFrame">
            Top Frame 970x50 
          </Ads>
          <Ads cssName="Billboard">
            Billboard 970x250
          </Ads>
          {/* INTERNAL CAMPAIGN */}
          <Ads cssName="Billboard">
            Horizontal 970x250<br/>
            (Internal campaign only)
          </Ads>
        {/* --------------- */}
        <LatestVideo/>
        <TopBrands/>

      </main>
    </>
  )
}
